/**
 * @File Name          : Newtestingclass.cls
 * @Description        : 
 * @Author             : ChangeMeIn@UserSettingsUnder.SFDoc
 * @Group              : 
 * @Last Modified By   : ChangeMeIn@UserSettingsUnder.SFDoc
 * @Last Modified On   : 06/03/2020, 4:07:20 pm
 * @Modification Log   : 
 * Ver       Date            Author      		    Modification
 * 1.0    06/03/2020   ChangeMeIn@UserSettingsUnder.SFDoc     Initial Version
**/
public class Newtestingclass {
    public static void test(){
        system.debug('akshdkjahsjkd');
        system.debug('usama khalid');
        system.debug('usama khalid');
    }
}